export const content = {
  name: "Cocinería Mary",
  tagline: "Cocina de casa, hecha con cariño",
  description:
    "Sabores sencillos, buenos momentos y una mesa para compartir. Bienvenidos a nuestra cocina.",
  logo: "/brand.svg",
  cover: "/cover.svg",
  address: "Dirección por confirmar",
  hours: "Horario por confirmar",
  mapsUrl: "",
  primary: "#244b40",
  secondary: "#bc643c",
  background: "#faf7f0",
  font: "serif",
  hideSoldOut: false,
  demo: true,
  allowDining: false,
  blocks: [
    "hero",
    "buttons",
    "menu",
    "promotion",
    "recommendations",
    "map",
    "feedback",
    "footer",
  ].map((id, order) => ({ id, order, visible: true })),
  buttons: [
    {
      id: "menu",
      text: "Ver Carta",
      icon: "book",
      url: "#carta",
      order: 0,
      active: true,
      style: "primary",
      action: "link",
    },
    {
      id: "reserve",
      text: "Reservar una mesa",
      icon: "calendar",
      url: "/reservas",
      order: 1,
      active: true,
      style: "outline",
      action: "link",
    },
    {
      id: "nearby",
      text: "Descubre nuestros recomendados",
      icon: "map",
      url: "/recomendados",
      order: 2,
      active: true,
      style: "soft",
      action: "link",
    },
  ],
  categories: [
    { id: "todos", name: "Para comenzar", order: 0, active: true },
    { id: "casa", name: "Platos de la casa", order: 1, active: true },
    { id: "mar", name: "Sabores del mar", order: 2, active: true },
    { id: "bebidas", name: "Para beber", order: 3, active: true },
  ],
  products: [
    {
      id: "empanadas",
      name: "Empanadas de queso",
      description:
        "Crujientes por fuera, suaves por dentro. Una buena forma de comenzar.",
      price: 4500,
      image: "/dish-empanada.svg",
      categoryId: "todos",
      available: true,
      tags: ["destacado"],
      order: 0,
    },
    {
      id: "ensalada",
      name: "Ensalada de la huerta",
      description: "Hojas frescas, tomates y el aliño de la casa.",
      price: 5900,
      image: "/dish-salad.svg",
      categoryId: "todos",
      available: true,
      tags: ["vegetariano"],
      order: 1,
    },
    {
      id: "cazuela",
      name: "Cazuela de la casa",
      description:
        "Un clásico reconfortante, con verduras y todo el sabor de la cocina casera.",
      price: 8900,
      image: "/dish-soup.svg",
      categoryId: "casa",
      available: true,
      tags: ["recomendación"],
      order: 2,
    },
    {
      id: "pastel",
      name: "Pastel de papas",
      description:
        "Puré dorado al horno y un sabroso relleno preparado en casa.",
      price: 8500,
      image: "/dish-empanada.svg",
      categoryId: "casa",
      available: true,
      tags: [],
      order: 3,
    },
    {
      id: "pescado",
      name: "Pescado con acompañamiento",
      description: "Pescado dorado, ensalada fresca y un toque de limón.",
      price: 10900,
      image: "/dish-fish.svg",
      categoryId: "mar",
      available: true,
      tags: ["recomendación"],
      order: 4,
    },
    {
      id: "mariscal",
      name: "Mariscal caliente",
      description: "Una preparación de mariscos para disfrutar sin apuro.",
      price: 11900,
      image: "/dish-soup.svg",
      categoryId: "mar",
      available: false,
      tags: [],
      order: 5,
    },
    {
      id: "limonada",
      name: "Limonada de la casa",
      description: "Limón, agua y frescura. Pregunta por las opciones del día.",
      price: 3200,
      image: "/dish-lemon.svg",
      categoryId: "bebidas",
      available: true,
      tags: ["nuevo"],
      order: 6,
    },
  ],
  promotion: {
    id: "mar-azul",
    name: "Una pausa junto al mar",
    text: "Conoce Cabañas Mar Azul y descubre una escapada para descansar.",
    image: "/coast.svg",
    buttonText: "Conocer este lugar",
    url: "/recomendados/cabanas-mar-azul",
    start: "2026-01-01",
    end: "2030-12-31",
    active: true,
  },
  partners: [
    {
      id: "mar-azul",
      slug: "cabanas-mar-azul",
      name: "Cabañas Mar Azul",
      category: "Dónde quedarse",
      description:
        "Un alojamiento de ejemplo para presentar la futura red de negocios locales. Este perfil no representa un negocio contratado.",
      image: "/coast.svg",
      location: "Ubicación por confirmar",
      mapsUrl: "",
      active: true,
      catalog: [
        {
          name: "Cabaña familiar",
          description:
            "Servicio de demostración. Disponibilidad por confirmar.",
          image: "/coast.svg",
        },
        {
          name: "Espacio para descansar",
          description: "Ejemplo de catálogo editable.",
          image: "/cover.svg",
        },
      ],
      buttons: [],
    },
  ],
};
